[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "openpyxl>=3.1.5",
    "python-dotenv>=1.1.1",
    "selenium>=4.34.2",
    "spotipy>=2.25.1",
]
